import Head from "next/head";
import Image from "next/image";
import { Box, Grid } from "@radix-ui/themes";
import Form from "../components/form";

export default function Preferences() {
  return (
    <>
      <Head>
        <title>LET ME COOK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-primary flex h-screen w-full flex-col items-center justify-center gap-12">
        <Grid columns="2" gap="0" width="100%" height="100%">
          <Box className="from-primary to-secondary align-center col-span-2 flex h-full flex-col justify-center bg-gradient-to-b p-6 sm:col-span-1 sm:p-12">
            <Form />
          </Box>

          <Box
            className="bg-light align-center hidden justify-center sm:flex"
            // direction="column"
            // gap="2"
          >
            <Image
              src="/assets/cooking-soup.svg"
              alt="soup"
              width="500"
              height="500"
            />
          </Box>
        </Grid>
      </div>
    </>
  );
}
